#should be in site bundle!!!
#parameters:
#    # override default ez ViewController - set TTL from twig template possible
#    ezpublish.controller.content.view.class: Cjw\PublishToolsBundle\Controller\Content\CjwPublishToolsViewController

services:
    cjw.publishtools.service.functions:
        class: Cjw\PublishToolsBundle\Services\PublishToolsService
        arguments: [@ezpublish.api.repository]

    cjw.publishtools.twig.functions:
        class: Cjw\PublishToolsBundle\Services\TwigFunctionsService
        arguments: [@cjw.publishtools.service.functions]
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    cjw.publishtools.formbuilder.functions:
        class: Cjw\PublishToolsBundle\Services\FormBuilderService
        arguments: ['@service_container']
    cjw.publishtools.formhandler.functions:
        class: Cjw\PublishToolsBundle\Services\FormHandlerService
        arguments: ['@service_container','@doctrine.orm.entity_manager','@mailer','@templating',@cjw.publishtools.formbuilder.functions]

#   define db tables as services
    db_table_ezinfocollection:
        class: Cjw\PublishToolsBundle\Entity\Ezinfocollection
    db_table_ezinfocollection_attribute:
        class: Cjw\PublishToolsBundle\Entity\EzinfocollectionAttribute
